AllCops:
  DefaultFormatter: pacman
  Exclude:
    - lib/tasks/auto_annotate_models.rake
  TargetRubyVersion: 3.2.0

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

# This appears to be a disagreement with prettier. Not quite sure if this isn't
# addressable somehow so just ignoring for now.
Style/BlockDelimiters:
  Exclude:
    - app/models/puzzles/maths/arithmetic_grid/times_table.rb
Style/MethodCalledOnDoEndBlock:
  Exclude:
    - app/models/puzzles/maths/arithmetic_grid/times_table.rb
